### ISSUE TITLE
Standard headers not found

### ISSUE THREAD

**Issue by nlohmann** [jasonmp85/homebrew-iwyu#4]
I installed iwyu using Homebrew. However, it seems not to find the standard headers:

```
$ iwyu json.hpp
json.hpp:41:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^
```

I read that this issue can somehow be avoided by copying the binary to the same folder that Clang lives in, but this doesn't work for me. Furthermore, I would expect the Homebrew formula to copy with such things.

Apart from that, thanks a lot for providing a formula!!

**Comment by jasonmp85** [comment]
What version of Xcode do you have installed? My formula creates a symlink to trick `include-what-you-use` into thinking it's installed alongside the headers, so it should find them automatically, but maybe your version of clang or the developer tools aren't where it expects. Can you provide more information so I can reproduce this?

**Comment by nlohmann** [comment]
Hi Jason, thanks for the quick response!

I use Xcode Version 7.0 beta (7A120f) on OS X Version 10.11 Beta (15A226f).

```
$ clang --version
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

Here is how iwyu is installed:

```
/usr/local/homebrew/Cellar/iwyu/
└── 0.4
    ├── INSTALL_RECEIPT.json
    ├── LICENSE.TXT
    ├── README.txt
    ├── bin
    │   ├── fix_include
    │   ├── include-what-you-use
    │   └── iwyu -> include-what-you-use
    └── lib
        └── clang
```

There may be an issue, because `lib/clang` is empty.

If you need further information, just ask.

Cheers,
Niels

**Comment by jasonmp85** [comment]
While I develop _on_ a Mac for my day job, I don't actually develop _for_ it, so I'm pretty conservative about OS updates, generally preferring to wait for the _x_.1 release of a given update before taking the plunge. And I don't think I've installed an OS X beta since back in the 10.0 days. So I probably won't devote time to figuring this out until October or so (and I doubt the Travis CI will catch the problem any time soon, since they're even more conservative).

That said, you can probably work around this by manually symlinking that lib directory to where it needs to point; check out the recipe for inspiration. Short-term, I could see whether there's any way to check `ln`'s status to catch when it fails to create the symlink, or just error out on newer/unexpected OS X versions.

If you figure out where the symlink needs to point for 10.11, let me know (possibly via a pull request) and I can test the change. If I can hack around it to maintain compatibility with previous OS X versions, I'll release as `v2.1.0`, otherwise this'll be in `v3.0.0`.

**Comment by jasonmp85** [comment]
`clang` used to say _(based on LLVM 3.6.0svn)_ at the end or something similar. It's odd that it no longer says that but I'm going to have to guess _Apple LLVM version 7.0.0_ actually means LLVM/clang 3.7, which won't release until August 21st.

`iwyu` has pretty tight coupling with `clang`, so I've been releasing a new major version for each minor `clang` bump. It sounds like [this bug][include-what-you-use/include-what-you-use#194] was only recently opened to address any incompatibilities with 3.7.

So based on all this, I'll punt on this until clang 3.7 is released and part of OS X 10.11. At that point it looks like we'll want a `homebrew-iwyu` `v3.0.0`.

**Comment by nlohmann** [comment]
I understand. I figured out that I can provide the include path as follows:

```
iwyu json.hpp $(clang -E -x c++ - -v < /dev/null 2>&1 | grep "^ " | sed '1d' | grep -v "(framework directory)" | sed 's/^ /-I/' | xargs)
```

On my machine, the include path is

```
-I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1 -I/usr/local/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include -I/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include
```

Unfortunately, I have no idea how to link this into the `iwyu` directory.

**Comment by jasonmp85** [comment]
Fixing El Cap support today.

**Comment by jasonmp85** [comment]
:rage3: I just blew over an hour trying to figure out why even with my El Cap fix, IWYU wasn't finding `<stdargs.h>`

\<stdarg**s**.h\>

GRRRRRR
